services:
    postgres:
        image: postgres:17
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: laravel
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
    mailpit:
      image: axllent/mailpit
      container_name: mailpit
      restart: unless-stopped
      ports:
          - "8025:8025"
          - "1025:1025"
    minio:
        image: minio/minio
        container_name: minio
        environment:
            MINIO_ROOT_USER: admin
            MINIO_ROOT_PASSWORD: password
        ports:
            - "9000:9000"
        volumes:
            - minio_data:/data
        command: server /data
        restart: always

    meilisearch:
        image: getmeili/meilisearch:v1.15
        container_name: meilisearch
        ports:
            - "7700:7700"
        environment:
            MEILI_MASTER_KEY: "xtDQX5FUKY40i2w-YUPjH2qNRMGcmxHCv7SLhDCSbe4"
        volumes:
            - meilisearch_data:/meili_data
        restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
  minio_data:
  meilisearch_data:
