services:
    postgres:
        image: postgres:17
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: laravel
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
    mailpit:
      image: axllent/mailpit
      container_name: mailpit
      restart: unless-stopped
      ports:
          - "8025:8025"
          - "1025:1025"
volumes:
  mariadb_data:
  redis_data:
  postgres_data:
